name: CICD of FER Flask Application on Azure
on:
  push:
    branches:
      - main  # Set your main branch name

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Application
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=development
          flask run --host=0.0.0.0 --port=5000 &

      - name: Wait for Flask to start
        run: |
          sleep 5  # Adjust as needed to wait for Flask to start

      - name: Test Flask Application
        id: test-flask
        run: |
          curl --retry 10 --retry-connrefused http://localhost:5000  # Adjust URL and port as needed

      - name: Stop Flask Application
        if: success()
        run: |
          pkill -f 'flask run'

      # Add further steps here based on your workflow requirements
